title: CSTATE-OCA
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://example.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Gateway
      category: Sites and Services
    - name: Backup Gateway
      category: Sites and Services
    - name: API
      description: The guts of the application.
      category: Uncategorized
    - name: Website
      description: The web frontend for the application.
      category: Uncategorized
      link: https://example.com/
    - name: Media Proxy
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#e9ecef"
  enableLastMod: true
  headerTextColor: white
  logo: /img/oca.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: true
  ok: "#008000"
  categories:
    - name: Sites and Services
      description: The main servers are located here.
      closed: true
    - name: Empty Category
  description: API OCA stands for "Application Programming Interface." It is a set
    of rules and protocols that allows different software applications to
    communicate with each other. APIs define the methods and data formats that
    applications can use to request and exchange information.
  enableCustomHTML: true
  useLargeHeaderDesign: true
